# Shell variables
# Generated by 'wal'
wallpaper='/home/voekreb/Documents/Wallpapers/daniel-frank-UoUqvOOwDh8-unsplash.jpg'

# Special
background='#141312'
foreground='#decabe'
cursor='#decabe'

# Colors
color0='#141312'
color1='#8D402A'
color2='#935236'
color3='#9F6D53'
color4='#B8845A'
color5='#B5896F'
color6='#C69676'
color7='#decabe'
color8='#9b8d85'
color9='#8D402A'
color10='#935236'
color11='#9F6D53'
color12='#B8845A'
color13='#B5896F'
color14='#C69676'
color15='#decabe'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
