--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/voekreb/Documents/Wallpapers/daniel-frank-UoUqvOOwDh8-unsplash.jpg"

-- Special
background="#141312"
foreground="#decabe"
cursor="#decabe"

-- Colors
color0="#141312"
color1="#8D402A"
color2="#935236"
color3="#9F6D53"
color4="#B8845A"
color5="#B5896F"
color6="#C69676"
color7="#decabe"
color8="#9b8d85"
color9="#8D402A"
color10="#935236"
color11="#9F6D53"
color12="#B8845A"
color13="#B5896F"
color14="#C69676"
color15="#decabe"
